server:
  port: 8090

spring:
  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/logs?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123abc
    driver-class-name: com.mysql.cj.jdbc.Driver

  #rabbitMQ
  rabbitmq:
    host: 192.168.15.129
    port: 5672
    username: admin
    password: 123abc
    virtual-host: log_host

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#custom attributes
my:
  rabbit:
    logExchange: log.exchange
    logQueue: log.queue
    routeKey: log
  file:
    filenamePrefix: logs_
    filepath: src/main/resources/logs