server:
  port: 9090

spring:
  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/db_logs_manager?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123abc
    driver-class-name: com.mysql.cj.jdbc.Driver

  #rabbitMQ
  rabbitmq:
    host: 192.168.15.129
    port: 5672
    username: admin
    password: 123abc
    virtual-host: log_host
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      location: /data/upload_tmp

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#logging
logging:
  level:
    com.logserver.mapper: debug