CREATE DATABASE `logs`;
USE `logs`;



DROP TABLE IF EXISTS `logs_info`;
CREATE TABLE `logs_info` (
	`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`guid` VARCHAR(120) NOT NULL COMMENT '真实Id',
	`description` VARCHAR(300) DEFAULT NULL COMMENT '描述信息',
	operator VARCHAR(120) DEFAULT NULL COMMENT '操作者',
	startTime DATETIME DEFAULT NULL COMMENT '操作时间',
	executeTime VARCHAR(120) DEFAULT NULL COMMENT '消耗时间',
	url VARCHAR(120) DEFAULT NULL COMMENT 'URL',
	methodType VARCHAR(120) DEFAULT NULL COMMENT '请求方法类型：get、post...',
	ip VARCHAR(120) DEFAULT NULL COMMENT 'IP地址',
	parameters VARCHAR(500) DEFAULT NULL COMMENT '请求参数',
	result VARCHAR(500) DEFAULT NULL COMMENT '请求返回的结果',
	device VARCHAR(300) DEFAULT NULL COMMENT '请求设备信息',
	createTime DATETIME DEFAULT NULL COMMENT '创建时间',
	createUser VARCHAR(120) DEFAULT NULL COMMENT '创建人',
	PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT '日志数据表';



DROP TABLE IF EXISTS `logs_error`;
CREATE TABLE `logs_error` (
	`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`guid` VARCHAR(120) NOT NULL COMMENT '真实Id',
	infoId VARCHAR(120) NOT NULL COMMENT '日志数据表Id',
	exceptionName VARCHAR(300) DEFAULT NULL COMMENT '异常名',
	exceptionMsg VARCHAR(500) DEFAULT NULL COMMENT '异常信息',
	createTime DATETIME DEFAULT NULL COMMENT '创建时间',
	createUser VARCHAR(120) DEFAULT NULL COMMENT '创建人',
	PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT '日志异常数据表';



DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`(
	`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`guid` VARCHAR(120) NOT NULL COMMENT '真实Id',
	`username` VARCHAR(120) DEFAULT NULL COMMENT '用户名',
	email VARCHAR(120) DEFAULT NULL COMMENT '电子邮箱',
	`password` VARCHAR(300) DEFAULT NULL COMMENT '密码',
	createTime DATETIME DEFAULT NULL COMMENT '创建时间',
	createUser VARCHAR(120) DEFAULT NULL COMMENT '创建人',
	PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT '用户表';